# Generated by Django 5.0.2 on 2025-05-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('manager', 'Manager'), ('team_lead', 'Team Lead'), ('senior_developer', 'Senior Developer'), ('developer', 'Developer'), ('junior_developer', 'Junior Developer'), ('hr_manager', 'HR Manager'), ('hr_executive', 'HR Executive'), ('accountant', 'Accountant'), ('receptionist', 'Receptionist'), ('office_assistant', 'Office Assistant')], max_length=100),
        ),
    ]
