# Generated by Django 5.0.2 on 2025-05-23 15:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_employee_id_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Chấm Công', 'verbose_name_plural': 'Chấm Công'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Phòng Ban', 'verbose_name_plural': 'Phòng Ban'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Nhân Viên', 'verbose_name_plural': 'Nhân Viên'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Phản Hồi', 'verbose_name_plural': 'Phản Hồi'},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Lương', 'verbose_name_plural': 'Lương'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Giờ vào'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Giờ ra'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Nhân viên'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='face_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Độ tin cậy nhận diện'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Có mặt'), ('absent', 'Vắng mặt'), ('late', 'Đi muộn'), ('half_day', 'Nửa ngày')], max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên phòng ban'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Lương cơ bản'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.department', verbose_name='Phòng ban'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(editable=False, max_length=10, unique=True, verbose_name='Mã nhân viên'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True, verbose_name='Mã hóa khuôn mặt'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='face_image',
            field=models.ImageField(upload_to='face_images/', verbose_name='Ảnh khuôn mặt'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Lương theo giờ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang làm việc'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(verbose_name='Ngày vào làm'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Lương tăng ca'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('manager', 'Quản Lý'), ('team_lead', 'Trưởng Nhóm'), ('senior_developer', 'Lập Trình Viên Cao Cấp'), ('developer', 'Lập Trình Viên'), ('junior_developer', 'Lập Trình Viên Mới'), ('hr_manager', 'Trưởng Phòng Nhân Sự'), ('hr_executive', 'Nhân Viên Nhân Sự'), ('accountant', 'Kế Toán'), ('receptionist', 'Lễ Tân'), ('office_assistant', 'Trợ Lý Văn Phòng')], max_length=100, verbose_name='Chức vụ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='standard_work_hours',
            field=models.IntegerField(default=8, verbose_name='Số giờ làm tiêu chuẩn'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='employee.employee', verbose_name='Nhân viên'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('suggestion', 'Đề Xuất Cải Thiện'), ('issue', 'Báo Cáo Vấn Đề'), ('complaint', 'Khiếu Nại'), ('other', 'Khác')], max_length=20, verbose_name='Loại phản hồi'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='Đã xử lý'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú xử lý'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xử lý'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='base_pay',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lương cơ bản'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Nhân viên'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.IntegerField(verbose_name='Tháng'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Giờ tăng ca'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='overtime_pay',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lương tăng ca'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='regular_hours_pay',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lương giờ làm'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='total_days',
            field=models.IntegerField(verbose_name='Tổng số ngày'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='total_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tổng lương'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='total_working_hours',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Tổng giờ làm'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='year',
            field=models.IntegerField(verbose_name='Năm'),
        ),
    ]
