# Generated by Django 5.0.2 on 2025-05-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_attendance_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Lương cơ bản'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Lương theo giờ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Lương tăng ca'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='base_pay',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Lương cơ bản'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='overtime_pay',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Lương tăng ca'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='regular_hours_pay',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Lương giờ làm'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='total_salary',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Tổng lương'),
        ),
    ]
